server_web:
    restart: always
    image: nginx
    volumes:
        - ./nginx_flask.conf:/etc/nginx/conf.d/default.conf
        - ./nginx.conf:/etc/nginx/nginx.conf
        # 打包后下行./webroot
        - ./webroot:/www/html/
        # 修改为对应的数据路径，为防止/www/html/被覆盖，需要指定每个挂载的文件夹
        - ${DATAPATH}:/www/html/report/
    privileged: true
    ports:
        - "86:86"
